# TODO: next nginx, prisma studio instead broken pgadmin, prisma migrate, graphql-codegen

version: '3.8'

networks:
  corp:
    driver: bridge

services:
  pgadmin:
    image: dpage/pgadmin4:4.21
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - corp
    restart: unless-stopped

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - corp
    environment:
      - POSTGRES_DB=castmate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  castmate-api:
    container_name: castmate-api
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/castmate-api/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: castmate-api:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'development'
      PORT: 4939
      PGHOST: 'postgres'
      PGDATABASE: 'castmate'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
    env_file:
      - ./apps/castmate-api/.env
      - ./.env.prod
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - corp
    restart: on-failure

  castmate-client:
    container_name: castmate-client
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/castmate-client/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: castmate-client:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    networks:
      - corp
    restart: on-failure

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - corp
    restart: on-failure

networks:
  corp:
    driver: bridge

volumes:
  postgres:
  pgadmin:
