module.exports = {
  projects: [
    '<rootDir>/apps/castmate-api',
    '<rootDir>/libs/prisma',
    '<rootDir>/libs/containers',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/chat',
    '<rootDir>/libs/chat-api',
    '<rootDir>/libs/room',
    '<rootDir>/libs/auth-api',
    '<rootDir>/libs/user-api',
    '<rootDir>/libs/connection-api',
    '<rootDir>/apps/castmate-client',
    '<rootDir>/libs/components',
    '<rootDir>/libs/icons',
    '<rootDir>/libs/layouts',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/user',
  ],
};